### ISSUE TITLE
Problem with example

### ISSUE THREAD

**Issue by Kenjyminamori** [eriksank/rpc-websocket#1]
Hi! 

There is an issue with examples on windows 10 64x: 

```
C:\path\to\my\app\node_modules\rpc-websocket\lib\rpc-socket.js:44
        ws.on('open', (function() {
          ^

TypeError: Cannot read property 'on' of undefined
    at RpcSocket.init (C:\path\to\my\app\node_modules\rpc-websocket\lib\rpc-socket.js:44:11)
    at RpcSocket.Emitter.removeAllListeners (C:\path\to\my\app\node_modules\rpc-websocket\node_modules\eventemitter4\index.js:146:22)
    at RpcSocket.close (C:\path\to\my\app\node_modules\rpc-websocket\lib\rpc-socket.js:161:14)
    at C:\path\to\my\app\node_modules\rpc-websocket\doc\examples\1-send-client.js:12:12
    atC:\path\to\my\app\node_modules\rpc-websocket\node_modules\eventemitter4\index.js:87:34
    at Array.forEach (native)
    at RpcSocket.Emitter.emit (C:\path\to\my\app\node_modules\rpc-websocket\node_modules\eventemitter4\index.js:86:44)
    at RpcSocket.<anonymous> (C:\path\to\my\app\node_modules\rpc-websocket\lib\rpc-socket.js:93:30)
    at Socket.Emitter.emit (C:\path\to\my\app\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
    at Socket.onPacket (C:\path\to\my\app\node_modules\engine.io-client\lib\socket.js:452:14)
```

**Comment by powercasper** [comment]
Same thing here (Sierra 10.12.3, Node v6.9.1)

**Comment by nicholasball** [comment]
Same issue here, seems to happen whenever you call ws.close()

**Comment by nicholasball** [comment]
Looks like it's a problem with **eventemitter4** and calling `removeAllListeners()` on line 141 of index.js.

Quick fix for **rpc-websocket** is to replace `this.removeAllListeners();` on line 161 of rpc-socket.js with:
```
        this.listeners={};
        this.onceListeners={};
        this.listenersToAnyEvent=[];
        this.event=null;
```
